import React,{useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{UploadCloud,RefreshCw,PlayCircle,CheckCircle2,XCircle,AlertTriangle,Eye}from'lucide-react'
import{fetchCases,fetchDocuments,fetchChecklist,updateChecklist,updateCaseStatus,uploadDocument,getDocumentSignedUrl,fetchOutputQueue,fetchOutputBatches,fetchOutputSessions,fetchOutputJobs,fetchOutputStrategies,processOutputQueue}from'./services/core'
import'./style.css'

const label={received:'Recibido',pending_client:'Pendiente cliente',human_validation:'En validación',ready_for_output:'Listo salida',completed:'Completado'}
function App(){
 const[view,setView]=useState('workspace'),[cases,setCases]=useState([]),[selected,setSelected]=useState(null),[docs,setDocs]=useState([]),[check,setCheck]=useState([]),[activeDoc,setActiveDoc]=useState(null),[docUrl,setDocUrl]=useState(null),[msg,setMsg]=useState('')
 async function load(){try{const c=await fetchCases();setCases(c);setSelected(s=>s?c.find(x=>x.id===s.id)||c[0]:c[0])}catch(e){setMsg(e.message)}}
 async function details(id){if(!id)return;try{const d=await fetchDocuments(id);setDocs(d);setCheck(await fetchChecklist(id));if(!activeDoc&&d[0])setActiveDoc(d[0])}catch(e){setMsg(e.message)}}
 useEffect(()=>{load()},[]);useEffect(()=>{if(selected)details(selected.id)},[selected?.id]);useEffect(()=>{if(activeDoc)getDocumentSignedUrl(activeDoc).then(setDocUrl).catch(e=>setMsg(e.message))},[activeDoc?.id])
 const missing=check.filter(i=>i.is_blocking&&i.status==='missing').length
 async function validateItem(i){await updateChecklist(i.id,{status:'validated',validation_status:'validated'});await details(selected.id)}
 async function ready(){if(missing>0){setMsg('Faltan documentos bloqueantes: '+missing);return}const u=await updateCaseStatus(selected.id,'ready_for_output');setCases(cases.map(c=>c.id===u.id?u:c));setSelected(u);setView('output');setMsg('Caso listo para salida.')}
 async function uploadFiles(files){if(!selected)return;for(const file of files){await uploadDocument({caseId:selected.id,organizationId:selected.organization_id,file})}await details(selected.id);await load();setMsg(files.length+' documento(s) cargados.')}
 return <div className="app"><aside><h1>Alfa‑Pyme</h1><p>Viewer + DnD MVP</p>{['workspace','upload','viewer','output'].map(v=><button className={view===v?'on':''}onClick={()=>setView(v)}key={v}>{v==='workspace'?'Workspace':v==='upload'?'Carga documental':v==='viewer'?'Visor documental':'Salidas'}</button>)}</aside><main><header><h2>{view==='workspace'?'Workspace':view==='upload'?'Carga documental':view==='viewer'?'Visor documental':'Salidas operativas'}</h2><button onClick={load}><RefreshCw size={16}/>Refrescar</button></header>{msg&&<div className="msg">{msg}<button onClick={()=>setMsg('')}>cerrar</button></div>}{view==='workspace'&&<Workspace cases={cases}selected={selected}setSelected={setSelected}check={check}docs={docs}validateItem={validateItem}ready={ready}setActiveDoc={setActiveDoc}setView={setView}missing={missing}/>} {view==='upload'&&<Upload selected={selected}cases={cases}setSelected={setSelected}uploadFiles={uploadFiles}/>} {view==='viewer'&&<Viewer selected={selected}docs={docs}activeDoc={activeDoc}setActiveDoc={setActiveDoc}docUrl={docUrl}check={check}/>} {view==='output'&&<Output/>}</main></div>}
function Workspace({cases,selected,setSelected,check,docs,validateItem,ready,setActiveDoc,setView,missing}){return <div className="grid"><section className="card"><h3>Casos</h3><table><thead><tr><th>Caso</th><th>Titular</th><th>Trámite</th><th>Estado</th></tr></thead><tbody>{cases.map(c=><tr onClick={()=>setSelected(c)}className={selected?.id===c.id?'sel':''}key={c.id}><td>{c.public_id}</td><td>{c.client_name}</td><td>{c.case_type}</td><td>{label[c.status]||c.status}</td></tr>)}</tbody></table></section><section className="panel"><h3>{selected?.public_id||'Sin caso'}</h3><p>{selected?.client_name}</p><h4>Checklist documental</h4>{check.map(i=><div className="item"key={i.id}>{i.status==='missing'?<XCircle/>:i.validation_status==='needs_review'?<AlertTriangle/>:<CheckCircle2/>}<div><b>{i.document_label}</b><small>{i.is_blocking?'Bloqueante':'No bloqueante'} · {i.status} · {i.validation_status}</small></div>{i.document_id&&i.validation_status!=='validated'&&<button onClick={()=>validateItem(i)}>Validar</button>}</div>)}<h4>Documentos</h4>{docs.map(d=><p key={d.id}>• {d.file_name} <b>{d.document_type}</b> <button onClick={()=>{setActiveDoc(d);setView('viewer')}}><Eye size={14}/> ver</button></p>)}<button className="primary"onClick={ready}>Confirmar y pasar a salida</button><p className="warn">{missing>0?'Faltan bloqueantes: '+missing:'Sin bloqueantes pendientes'}</p></section></div>}
function Upload({selected,cases,setSelected,uploadFiles}){const[over,setOver]=useState(false);return <div className="card upload"><h3>Subida múltiple documental</h3><select value={selected?.id||''}onChange={e=>setSelected(cases.find(c=>c.id===e.target.value))}>{cases.map(c=><option key={c.id}value={c.id}>{c.public_id} · {c.client_name}</option>)}</select><div className={'drop '+(over?'over':'')}onDragOver={e=>{e.preventDefault();setOver(true)}}onDragLeave={()=>setOver(false)}onDrop={e=>{e.preventDefault();setOver(false);uploadFiles([...e.dataTransfer.files])}}><UploadCloud size={42}/><b>Arrastra aquí varios PDF/imágenes</b><p>o selecciona archivos</p><input multiple type="file"accept=".pdf,image/*"onChange={e=>uploadFiles([...e.target.files])}/></div><p>Prueba nombres: dni_comprador.pdf, permiso.pdf, factura.pdf, pago.pdf. Luego reemplazaremos esto por OCR/IA.</p></div>}
function Viewer({selected,docs,activeDoc,setActiveDoc,docUrl,check}){return <div className="viewer"><section className="doclist"><h3>{selected?.public_id}</h3>{docs.map(d=><button className={activeDoc?.id===d.id?'on':''}onClick={()=>setActiveDoc(d)}key={d.id}>{d.file_name}<small>{d.document_type} · conf. {d.confidence}</small></button>)}</section><section className="docview">{docUrl?activeDoc?.file_type?.startsWith('image/')?<img src={docUrl}/>:<iframe src={docUrl}/>:<p>Selecciona documento.</p>}</section><section className="extract"><h3>Extracción / confianza</h3>{activeDoc&&<><p><b>Tipo:</b> {activeDoc.document_type}</p><p><b>Confianza:</b> {activeDoc.confidence}</p><p><b>OCR:</b> {activeDoc.ocr_text}</p>{Number(activeDoc.confidence)<0.85&&<div className="low">Baja confianza: requiere revisión humana.</div>}</>}<h4>Checklist</h4>{check.map(i=><p key={i.id}>• {i.document_label}: <b>{i.validation_status}</b></p>)}</section></div>}
function Output(){const[tab,setTab]=useState('queue'),[q,setQ]=useState([]),[b,setB]=useState([]),[s,setS]=useState([]),[j,setJ]=useState([]),[st,setSt]=useState([]),[msg,setMsg]=useState('');async function load(){setQ(await fetchOutputQueue());setB(await fetchOutputBatches());setS(await fetchOutputSessions());setJ(await fetchOutputJobs());setSt(await fetchOutputStrategies())}useEffect(()=>{load()},[]);async function process(){setMsg(JSON.stringify(await processOutputQueue()));await load()}return <div><div className="bar"><button className="primary"onClick={process}><PlayCircle size={16}/>Procesar cola</button><button onClick={load}>Refrescar</button></div>{msg&&<div className="msg">{msg}</div>}<div className="tabs">{['queue','batches','sessions','jobs','strategies'].map(x=><button className={tab===x?'on':''}onClick={()=>setTab(x)}key={x}>{x}</button>)}</div>{tab==='queue'&&<List title="Cola de salida" rows={q} cols={['case_type','output_route','output_mode','status','destination_system']}/>} {tab==='batches'&&<List title="Lotes CSV" rows={b} cols={['file_name','case_type','total_cases','status','destination_system']}/>} {tab==='sessions'&&<List title="Sesiones Copiloto" rows={s} cols={['session_name','case_type','total_cases','status','output_route']}/>} {tab==='jobs'&&<List title="Jobs API/RPA" rows={j} cols={['output_route','destination_system','status','attempts']}/>} {tab==='strategies'&&<List title="Estrategias" rows={st} cols={['case_type','output_route','output_mode','grouping_strategy','destination_system']}/>}</div>}
function List({title,rows,cols}){return <section className="card"><h3>{title}</h3>{rows.length?rows.map(r=><div className="row"key={r.id}>{cols.map(c=><span key={c}>{String(r[c]??'')}</span>)}</div>):<p>Sin registros.</p>}</section>}
createRoot(document.getElementById('root')).render(<App/>)
